hmrc/pension-administrator-frontend

.g8/intPage/app/controllers/$routeFile;format="packaged"$/$className$Controller.scala
.g8/intPage/app/views/$routeFile;format="packaged"$/$className__decap$.scala.html
.g8/intPage/generated-test/views/$routeFile;format="packaged"$/$className$ViewSpec.scala
.g8/optionsPage/app/controllers/$routeFile;format="packaged"$/$className$Controller.scala
.g8/optionsPage/app/views/$routeFile;format="packaged"$/$className__decap$.scala.html
.g8/optionsPage/generated-test/views/$routeFile;format="packaged"$/$className$ViewSpec.scala
.g8/page/app/views/$routeFile;format="packaged"$/$className__decap$.scala.html
.g8/page/generated-test/views/$routeFile;format="packaged"$/$className$ViewSpec.scala
.g8/questionPage/app/views/$routeFile;format="packaged"$/$className__decap$.scala.html
.g8/questionPage/generated-test/views/$routeFile;format="packaged"$/$className$ViewSpec.scala
.g8/yesNoPage/app/views/$routeFile;format="packaged"$/$className__decap$.scala.html
.g8/yesNoPage/generated-test/views/$routeFile;format="packaged"$/$className$ViewSpec.scala
app/views/register/company/companyDetails.scala.html
test/generators/Generators.scala
test/views/register/company/CompanyDetailsViewSpec.scala

Fixed existing pages
Fixed intPage compilation issues
Fixed optionsPage

PODS-617: Scaffold not creating back link on new forms

---

app/controllers/register/company/CompanyAddressYearsController.scala
app/forms/register/company/CompanyAddressYearsFormProvider.scala
app/identifiers/register/company/CompanyAddressYearsId.scala
app/models/register/company/CompanyAddressYears.scala
app/utils/CheckYourAnswersHelper.scala
app/views/register/company/companyAddressYears.scala.html
conf/company.routes
conf/messages.en
migrations/applied_migrations/CompanyAddressYears.sh
test/controllers/register/company/CompanyAddressYearsControllerSpec.scala
test/forms/register/company/CompanyAddressYearsFormProviderSpec.scala
test/views/register/company/CompanyAddressYearsViewSpec.scala

Set field names and messages
Added secondary header and back

PODS-465: Company - How long at address?

---

app/controllers/register/company/AddCompanyDirectorsController.scala
app/identifiers/register/company/CompanyDirectorsId.scala
app/models/Person.scala
app/views/components/person_list.scala.html
app/views/register/company/addCompanyDirectors.scala.html
test/connectors/FakeDataCacheConnector.scala
test/controllers/register/company/AddCompanyDirectorsControllerSpec.scala
test/utils/FakeNavigator.scala
test/views/behaviours/PeopleListBehaviours.scala
test/views/register/company/AddCompanyDirectorsViewSpec.scala

Set delete/edit to pending
Controller spec
Amended delete link
Error in controller

PODS-471: Add a director

---

app/assets/stylesheets/partials/_shame.scss
app/connectors/RegistrationConnector.scala
app/controllers/register/individual/IndividualDetailsCorrectController.scala
app/utils/CheckYourAnswersHelper.scala
app/views/register/individual/individualDetailsCorrect.scala.html
test/controllers/register/individual/IndividualDetailsCorrectControllerSpec.scala

registerWithIdIndividual connector
View

PODS-703: Individual Details Correct

---

app/connectors/MicroserviceCacheConnector.scala
app/filters/FiltersWithWhitelist.scala
app/filters/WhitelistFilter.scala
conf/application.conf
project/FrontendBuild.scala

Add whitelist filter
Add application loader to allow loading base64 encoded config

Amend endpoint for microservice cache connector

---

app/controllers/register/individual/CheckYourAnswersController.scala
app/identifiers/register/individual/CheckYourAnswersId.scala
app/utils/CheckYourAnswersHelper.scala
app/views/components/answer_row.scala.html
conf/individual.routes
conf/messages.en
test/controllers/register/individual/CheckYourAnswersControllerSpec.scala
test/views/behaviours/CheckYourAnswersBehaviours.scala

PODS-522: Individual Check Your Answers

---

app/controllers/register/BusinessTypeController.scala
app/controllers/register/company/CompanyAddressController.scala
app/forms/register/BusinessTypeFormProvider.scala
app/identifiers/register/BusinessTypeId.scala
app/models/Organisation.scala
app/models/register/BusinessType.scala
app/views/register/businessType.scala.html
conf/app.routes
conf/messages.en
conf/register.routes
migrations/applied_migrations/BusinessType.sh
test/controllers/register/BusinessTypeControllerSpec.scala
test/controllers/register/company/CompanyAddressControllerSpec.scala
test/forms/register/BusinessTypeFormProviderSpec.scala
test/models/OrganisationSpec.scala
test/views/register/BusinessTypeViewSpec.scala

Model and form
View
Controller
Tidy up and remove Individual
BusinessType to OrganisationTypeEnum mapping

PODS-702: Business Type

---

app/assets/stylesheets/partials/_forms.scss
app/assets/stylesheets/partials/_lists.scss
app/assets/stylesheets/pensionadministratorfrontend-app.scss
app/controllers/Journey.scala
app/controllers/register/DeclarationController.scala
app/controllers/register/company/WhatYouWillNeedController.scala
app/forms/mappings/CheckboxMapping.scala
app/forms/register/DeclarationFormProvider.scala
app/identifiers/register/DeclarationId.scala
app/views/register/declaration.scala.html
conf/company.routes
conf/messages.en
conf/register.routes
migrations/applied_migrations/Declaration.sh
test/controllers/register/DeclarationControllerSpec.scala
test/forms/behaviours/CheckboxBehaviour.scala
test/forms/register/DeclarationFormProviderSpec.scala
test/views/ViewSpecBase.scala
test/views/behaviours/QuestionViewBehaviours.scala
test/views/register/DeclarationViewSpec.scala

View
Controller and journey type

PODS-560 Declaration Part 1

---

app/controllers/register/company/CheckYourAnswersController.scala
app/controllers/register/company/CompanyAddressListController.scala
app/controllers/register/company/CompanyReviewController.scala
app/controllers/register/company/ConfirmCompanyDetailsController.scala
app/forms/register/company/CompanyDetailsFormProvider.scala
app/models/register/company/CompanyDetails.scala
app/utils/CheckYourAnswersHelper.scala
app/utils/navigators/RegisterCompanyNavigator.scala
app/views/register/company/companyDetails.scala.html
app/views/register/company/confirmCompanyDetails.scala.html
conf/application.conf
conf/messages.en
test/controllers/ControllerSpecBase.scala
test/controllers/register/company/CheckYourAnswersControllerSpec.scala
test/controllers/register/company/CompanyAddressListControllerSpec.scala
test/controllers/register/company/CompanyDetailsControllerSpec.scala
test/controllers/register/company/CompanyReviewControllerSpec.scala
test/controllers/register/company/ConfirmCompanyDetailsControllerSpec.scala
test/controllers/register/company/directors/DirectorAddressYearsControllerSpec.scala
test/controllers/register/company/directors/DirectorContactDetailsControllerSpec.scala
test/controllers/register/company/directors/DirectorNinoControllerSpec.scala
test/controllers/register/company/directors/DirectorPreviousAddressControllerSpec.scala
test/controllers/register/company/directors/DirectorPreviousAddressPostCodeLookupControllerSpec.scala
test/controllers/register/company/directors/DirectorUniqueTaxReferenceControllerSpec.scala
test/forms/register/company/CompanyDetailsFormProviderSpec.scala
test/utils/navigators/RegisterCompanyNavigatorSpec.scala
test/views/register/company/CompanyDetailsViewSpec.scala
test/views/register/company/ConfirmCompanyDetailsViewSpec.scala

Removed CompanyDetails.companyName
Fixed merge conflicts
Business Details read only on CYA

PODS-828: Check your answers navigation

---

app/config/FrontendAppConfig.scala
app/connectors/PensionsSchemeConnector.scala
app/connectors/RegistrationConnector.scala
app/controllers/register/DeclarationFitAndProperController.scala
app/controllers/register/DuplicateRegistrationController.scala
app/controllers/register/company/ConfirmCompanyDetailsController.scala
app/controllers/register/individual/IndividualDetailsCorrectController.scala
app/identifiers/register/RegistrationInfoId.scala
app/models/RegisterWithIdResponse.scala
app/models/RegistrationInfo.scala
conf/application.conf
test/connectors/FakeDataCacheConnector.scala
test/connectors/PensionsSchemeConnectorSpec.scala
test/connectors/RegistrationConnectorSpec.scala
test/controllers/actions/FakeDataRetrievalAction.scala
test/controllers/register/DeclarationFitAndProperControllerSpec.scala
test/controllers/register/company/ConfirmCompanyDetailsControllerSpec.scala
test/controllers/register/individual/IndividualDetailsCorrectControllerSpec.scala

ConfirmCompanyDetailsController saves reg info
IndividualDetailsCorrectController saves reg info
Connector (incomplete)
Connector (incomplete)
Registration Info included NINO/UTR
Pensions scheme connector
Fixed merge conflicts
Hooked into controllers

PODS-774: Send user answers from front end to back end

---

app/forms/register/advisor/AdvisorDetailsFormProvider.scala
app/models/register/advisor/AdvisorDetails.scala
app/utils/CheckYourAnswersHelper.scala
app/views/register/advisor/advisorDetails.scala.html
conf/messages.en
test/controllers/register/advisor/AdvisorDetailsControllerSpec.scala
test/controllers/register/advisor/CheckYourAnswersControllerSpec.scala
test/forms/register/advisor/AdvisorDetailsFormProviderSpec.scala
test/identifiers/register/DeclarationWorkingKnowledgeIdSpec.scala
test/views/register/advisor/AdvisorDetailsViewSpec.scala

Reverts hmrc/pension-administrator-frontend#127

Revert "PODS-865 added phone number to adviser details page"

---

app/config/FrontendAppConfig.scala
app/connectors/AuthenticationConnector.scala
conf/application.conf
test/connectors/AuthenticationConnectorSpec.scala

Reverts hmrc/pension-administrator-frontend#172

Revert "Pods 1047"

---

app/config/FrontendAppConfig.scala
app/connectors/TaxEnrolmentsConnector.scala
app/controllers/register/DeclarationFitAndProperController.scala
app/models/register/KnownFacts.scala
app/utils/KnownFactsRetrieval.scala
conf/application.conf
test/connectors/TaxEnrolmentsConnectorSpec.scala
test/controllers/register/DeclarationFitAndProperControllerSpec.scala
test/utils/KnownFactsRetrievalSpec.scala

Reverts hmrc/pension-administrator-frontend#177

Revert "Change to endpoint including move of identifier to request body for e…"

---

app/config/FrontendAppConfig.scala
app/connectors/EnrolmentStoreConnector.scala
app/controllers/register/DeclarationFitAndProperController.scala
conf/application.conf
test/connectors/EnrolmentStoreConnectorSpec.scala
test/controllers/register/DeclarationFitAndProperControllerSpec.scala

Reverts hmrc/pension-administrator-frontend#176

Revert "Switch endpoint to tax-enrolments"

---

app/config/FrontendAppConfig.scala
app/controllers/InterceptPSAController.scala
app/views/interceptPSA.scala.html
conf/app.routes
conf/application.conf
conf/messages.en
migrations/applied_migrations/InterceptPSA.sh
test/controllers/InterceptPSAControllerSpec.scala
test/views/InterceptPSAViewSpec.scala

Isolated page. Work to follow to hook up with Auth Action

PODS-1078: Intercept page for those already with psa

---

app/utils/navigators/RegisterCompanyNavigator.scala
test/controllers/register/company/CompanyContactAddressListControllerSpec.scala
test/utils/navigators/RegisterCompanyNavigatorSpec.scala
test/utils/package.scala

RegisterCompanyNavigator
RegisterCompanyNavigator2
CheckYourAnswers

PODS-1053: Company contact address navigation

---

app/controllers/register/partnership/partners/PartnerContactDetailsController.scala
conf/partners.routes
conf/partnership.routes
test/controllers/register/partnership/partners/PartnerContactDetailsControllerSpec.scala

Skeleton of partner contact details controller

Pods 512: Reg PSA - Partnership - Partner - contact details

---

app/controllers/PersonDetailsController.scala
app/controllers/register/partnership/partners/PartnerDetailsController.scala
app/viewmodels/PersonDetailsViewModel.scala
app/views/personDetails.scala.html
conf/messages.en
conf/partners.routes
test/controllers/PersonDetailsControllerBehaviour.scala
test/controllers/PersonDetailsControllerSpec.scala
test/controllers/register/partnership/partners/PartnerDetailsControllerSpec.scala
test/views/PersonDetailsViewSpec.scala

PersonDetailsController
DirectorDetailsController
PartnerDetailsController
PartnerDetailsControllerSpec
Tidy up

PODS-502: Partnership - Partner - Name and DOB details

---

app/controllers/ConfirmDeleteController.scala
app/controllers/register/ConfirmDeleteController.scala
app/controllers/register/company/directors/ConfirmDeleteDirectorController.scala
app/controllers/register/partnership/partners/ConfirmDeletePartnerController.scala
app/viewmodels/ConfirmDeleteViewModel.scala
app/views/confirmDelete.scala.html
conf/messages.en
conf/partners.routes
migrations/applied_migrations/ConfirmDeletePartner.sh
test/controllers/ConfirmDeleteControllerSpec.scala
test/controllers/ControllerSpecBase.scala
test/controllers/partners/ConfirmDeletePartnerControllerSpec.scala
test/controllers/register/company/directors/CompanyDirectorAddressListControllerSpec.scala
test/controllers/register/company/directors/ConfirmDeleteDirectorControllerSpec.scala
test/controllers/register/company/directors/DirectorAddressControllerSpec.scala
test/controllers/register/company/directors/DirectorPreviousAddressListControllerSpec.scala
test/controllers/register/individual/IndividualContactAddressControllerSpec.scala
test/controllers/register/individual/IndividualPreviousAddressControllerSpec.scala
test/views/ConfirmDeleteViewSpec.scala

Generic ConfirmDeleteController invoked by Partners and Directors

Pods 559: Reg PSA - Partnership - Confirm partner deletion

---

app/config/FrontendAppConfig.scala
app/controllers/PensionSchemePractitionerController.scala
app/controllers/actions/AuthAction.scala
app/views/pensionSchemePractitioner.scala.html
conf/app.routes
conf/application.conf
conf/messages.en
test/controllers/PensionSchemePractitionerControllerSpec.scala
test/controllers/actions/AuthActionSpec.scala
test/views/PensionSchemePractitionerViewSpec.scala

PensionSchemePractitionerController
Routes
Adding enrolment logic to auth action

PODS-1237: Inhibit PSPs from using PODS service

---

app/forms/BusinessDetailsFormProvider.scala
app/forms/PersonDetailsFormProvider.scala
app/forms/mappings/AddressMapping.scala
app/forms/mappings/Constraints.scala
app/forms/mappings/Formatters.scala
app/forms/mappings/Mappings.scala
app/forms/mappings/PhoneNumberMapping.scala
test/forms/AddressFormProviderSpec.scala
test/forms/PersonDetailsFormProviderSpec.scala
test/forms/behaviours/AddressBehaviours.scala
test/forms/behaviours/StringFieldBehaviours.scala
test/forms/mappings/AddressMappingSpec.scala
test/forms/mappings/MappingsSpec.scala

Optional text fields
Standardise text
Refactor for whitespace rather than space
Address
Refactor
Tidy up

PODS-1253: Trim space from form text fields

---

app/assets/stylesheets/partials/_shame.scss
app/views/components/answer_section.scala.html
conf/application.conf

Changed font size and table width to match scheme, updated assets frontend

PODS-1273: CYA Styling issues

---

app/config/FrontendAppConfig.scala
app/connectors/SubscriptionConnector.scala
app/models/PsaSubscription/PsaSubscription.scala
app/utils/HttpResponseHelper.scala
conf/application.conf
test/base/JsonFileReader.scala
test/connectors/SubscriptionConnectorSpec.scala
test/utils/testhelpers/PsaSubscriptionBuilder.scala

Please do NOT delete the branch after merging. This is WIP

PODS-1669 Added model for PSA details and updated connector

---

app/controllers/register/company/AreYouInUKController.scala
app/forms/register/AreYouInUKFormProvider.scala
app/identifiers/register/company/AreYouInUKId.scala
app/views/register/company/areYouInUK.scala.html
conf/company.routes
conf/messages.en
test/controllers/register/company/AreYouInUKControllerSpec.scala
test/forms/register/AreYouInUKFormProviderSpec.scala
test/views/register/company/AreYouInUKViewSpec.scala

PODS-1342 PSA Company Are you in the UK

---

app/identifiers/register/company/CompanyNameId.scala

PODS-1044 : added company name identifier

PODS-1044 : added company name identifier

---

app/identifiers/register/company/CompanyRegisteredAddressId.scala

PODS-1372 : added company registered nonuk address identifiers

PODS-1372 : added company registered nonuk address identifiers

---

app/controllers/register/CompanyNameController.scala
app/forms/CompanyNameFormProvider.scala
app/forms/mappings/CompanyNameMapping.scala
app/viewmodels/CompanyNameViewModel.scala
app/views/companyName.scala.html
conf/messages.en
test/controllers/register/CompanyNameControllerSpec.scala
test/forms/mappings/CompanyNameMappingSpec.scala
test/views/CompanyNameViewSpec.scala
test/views/address/PostcodeLookupViewSpec.scala
test/views/behaviours/StringViewBehaviours.scala

Reverts hmrc/pension-administrator-frontend#344

Revert "Revert "Company name common component""

---

app/controllers/register/RegisterAsBusinessController.scala
app/forms/register/RegisterAsBusinessFormProvider.scala
app/identifiers/register/RegisterAsBusinessId.scala
app/views/components/input_yes_no.scala.html
app/views/register/registerAsBusiness.scala.html
conf/messages.en
conf/register.routes
test/controllers/actions/FakeUnAuthorisedAction.scala
test/controllers/behaviours/ControllerWithQuestionPageBehaviours.scala
test/controllers/register/RegisterAsBusinessControllerSpec.scala
test/forms/register/RegisterAsBusinessFormProviderSpec.scala
test/utils/package.scala
test/views/register/RegisterAsBusinessViewSpec.scala

View complete
Controller complete
Refactor view after running

PODS-1672: are you registering as a business or as an individual?

---

app/controllers/register/individual/IndividualRegisteredAddressController.scala
test/controllers/register/individual/IndividualRegisteredAddressControllerSpec.scala

PODS-1727 : compilation because of merge issue

PODS-1727 : compilation because of merge issue

---

app/connectors/AddressLookupConnector.scala
app/models/TolerantAddress.scala
test/connectors/AddressLookupConnectorSpec.scala
test/models/reads/TolerantAddressReadsSpec.scala

… addresses from address lookup list

PODS-1844 Stop NoAddressLinesException Pager Duties

---

app/controllers/register/individual/IndividualDetailsCorrectController.scala
app/models/TolerantAddress.scala
app/utils/CheckYourAnswersHelper.scala
app/utils/countryOptions/CountryOptions.scala
app/views/register/individual/individualDetailsCorrect.scala.html
test/controllers/register/individual/CheckYourAnswersControllerSpec.scala
test/controllers/register/individual/IndividualDetailsCorrectControllerSpec.scala
test/views/register/individual/IndividualDetailsCorrectViewSpec.scala

CheckYourAnswersHelper
Individual details correct
Deprecated old methods

PODS-1807: Base changes and Individual Details Correct

---

app/views/main_template.scala.html
conf/messages.en
test/views/AlreadyDeletedViewSpec.scala
test/views/behaviours/ViewBehaviours.scala
test/views/register/company/directors/ConfirmDeleteDirectorViewSpec.scala

PODS-2175: browser title updated as per standard

---

app/connectors/SubscriptionConnector.scala
app/controllers/PsaDetailsController.scala
test/connectors/SubscriptionConnectorSpec.scala
test/controllers/PsaDetailsControllerSpec.scala

PODS-2208 : Create/Update connector method in pension-administrator-frontend to consume psa details as user answers

PODS-2208 : Create/Update connector method in pension-administrator-frontend to consume psa details as user answers

---

app/models/Mode.scala
app/utils/Navigator.scala

PODS-2244: PSA variances - Create "UpdateMode" on Pension-Administrator-Frontend

PODS-2244: PSA variances - Create "UpdateMode" on Pension-Administrator-Frontend

---

app/controllers/PsaDetailsController.scala
app/controllers/actions/AuthAction.scala
app/identifiers/UpdateModeId.scala
test/controllers/PsaDetailsControllerSpec.scala
test/controllers/actions/AuthActionSpec.scala

PODS-2263: PSA variances - update the AuthAction to redirect to the update journeys pages

PODS-2263: PSA variances - update the AuthAction to redirect to the update journeys pages

---

app/controllers/PsaDetailsController.scala
app/utils/UserAnswers.scala
app/viewmodels/PsaViewDetailsViewModel.scala
app/views/psa_details.scala.html
conf/application.conf
conf/messages.en
test/controllers/PsaDetailsControllerSpec.scala
test/utils/UserAnswersSpec.scala
test/views/PsaDetailsViewSpec.scala

PODS-2242 : PSA variances - Update PSA details page to include 'Go to Declarations button'

PODS-2242 : PSA variances - Update PSA details page to include 'Go to Declarations button'

---

conf/directors.routes

PODS-2250 : fixed the mode

---

app/controllers/Variations.scala
app/controllers/register/DeclarationWorkingKnowledgeController.scala
app/controllers/register/VariationWorkingKnowledgeController.scala
app/forms/register/VariationWorkingKnowledgeFormProvider.scala
app/identifiers/register/VariationWorkingKnowledgeId.scala
app/views/register/variationWorkingKnowledge.scala.html
conf/messages.en
conf/register.routes
test/controllers/register/DeclarationWorkingKnowledgeControllerSpec.scala
test/controllers/register/VariationWorkingKnowledgeControllerSpec.scala
test/forms/register/VariationWorkingKnowledgeFormProviderSpec.scala
test/views/register/VariationWorkingKnowledgeViewSpec.scala

PODS-2330 : PSA variations - create a page for working knowledge declaration

PODS-2330 : PSA variations - create a page for working knowledge declaration

---

app/controllers/vary/DeclarationVariationController.scala
app/forms/vary/DeclarationVariationFormProvider.scala
app/views/vary/declarationFitAndProper.scala.html
app/views/vary/declarationVariation.scala.html
conf/messages.en
conf/vary.routes
test/controllers/register/DeclarationControllerSpec.scala
test/controllers/register/DeclarationFitAndProperControllerSpec.scala
test/controllers/vary/DeclarationFitAndProperControllerSpec.scala
test/controllers/vary/DeclarationVariationControllerSpec.scala
test/forms/vary/DeclarationFitAndProperFormProviderSpec.scala
test/forms/vary/DeclarationVariationFormProviderSpec.scala
test/views/ViewSpecBase.scala
test/views/vary/DeclarationVariationViewSpec.scala

PODS-2194 : PSA variances - Create a screen for declaration summary

PODS-2194 : PSA variances - Create a screen for declaration summary

---

app/controllers/IncompleteChangesController.scala
app/controllers/register/IncompleteChangesController.scala
app/views/register/incompleteChanges.scala.html
conf/messages.en
conf/register.routes
test/controllers/register/IncompleteChangesControllerSpec.scala
test/controllers/register/VariationNoLongerFitAndProperControllerSpec.scala
test/views/register/IncompleteChangesViewSpec.scala

PODS-2432 : Service improvement - PSA variations - Create page for 'you have incomplete PSA changes' interrupt page

PODS-2432 : Service improvement - PSA variations - Create page for 'you have incomplete PSA changes' interrupt page	

---

conf/application.conf

PODS-2673: feedback survey updated

PODS-2673: feedback survey updated

---

conf/messages.en

PODS-2513: PSA variations Contact Address page content changes

---

app/controllers/register/DuplicateRegistrationController.scala
app/views/components/link.scala.html
app/views/register/duplicateRegistration.scala.html
conf/messages.en
conf/register.routes
test/controllers/register/DuplicateRegistrationControllerSpec.scala
test/views/behaviours/ViewBehaviours.scala
test/views/register/DuplicateRegistrationViewSpec.scala
test/views/register/SubmissionInvalidViewSpec.scala

PODS-2634 : DEV ticket to create page and include nav for individuals that get a '403 PSAactiveforanotherBP' on PSA subscription

PODS-2634 : DEV ticket to create page and include nav for individuals that get a '403 PSAactiveforanotherBP' on PSA subscription

---

app/forms/PersonDetailsFormProvider.scala
app/forms/mappings/Constraints.scala
app/views/components/input_date.scala.html
conf/application.conf
conf/messages.en
test/forms/PersonDetailsFormProviderSpec.scala
test/forms/mappings/ConstraintsSpec.scala

PODS 2812: Pension admin date fields (all) - You cannot get into all date fields

PODS 2812: Pension admin date fields (all) - You cannot get into all date fields

---

conf/application.conf

Make sure the service doesn't try to render messages in Welsh

Disable support for Welsh

---

app/controllers/register/company/ConfirmCompanyDetailsController.scala
app/controllers/register/partnership/ConfirmPartnershipDetailsController.scala

PODS-3579 Change register with ID endpoint in back-end service to remove brackets

---

app/connectors/EmailConnector.scala
app/controllers/Retrievals.scala
app/controllers/register/ConfirmationController.scala
app/controllers/register/DeclarationController.scala
app/views/register/confirmation.scala.html
conf/messages.en
test/connectors/EmailConnectorSpec.scala
test/controllers/RetrievalsSpec.scala
test/controllers/register/ConfirmationControllerSpec.scala
test/controllers/register/DeclarationControllerSpec.scala
test/views/register/ConfirmationViewSpec.scala

Reverts hmrc/pension-administrator-frontend#698

Revert "Pods 4264"

---

app/connectors/EmailConnector.scala
app/controllers/Retrievals.scala
app/controllers/register/ConfirmationController.scala
app/controllers/register/DeclarationController.scala
app/views/register/confirmation.scala.html
conf/messages.en
test/connectors/EmailConnectorSpec.scala
test/controllers/RetrievalsSpec.scala
test/controllers/register/ConfirmationControllerSpec.scala
test/controllers/register/DeclarationControllerSpec.scala
test/views/register/ConfirmationViewSpec.scala

Reverts hmrc/pension-administrator-frontend#699

Revert "Revert "Pods 4264""

---

app/controllers/register/AreYouInUKController.scala
app/controllers/register/individual/IndividualAreYouInUKController.scala
app/controllers/register/individual/NonUKAdministratorController.scala
app/views/register/individual/nonUKAdministrator.scala.html
conf/individual.routes
conf/messages.en
test/controllers/register/individual/IndividualAreYouInUKControllerSpec.scala

Code:
- Added new page to display when an individual registering as a PSA declares that they are not a UK resident

PODS-9186: Non UK registration change

---

app/config/FrontendAppConfig.scala
app/connectors/DeregistrationConnector.scala
conf/application.conf
test/connectors/DeregistrationConnectorSpec.scala

deregister-psa to deregister-psa-self

PODS-10108 - Replace Delete route
